name = "kawai/web"
version = "0.3.0"
description = "KawaiWeb, framework web minimalista com templates HTML e middleware para KawaiLang"
entry = "web.🎀"
license = "MIT"

[files]
kawai = ["web.🎀"]

[compat]
kawailang = ">=0.1.94"
